import type { Metadata } from "next";

import { Toaster } from "@/components/ui/toaster";
import { Navbar } from "@/components/navbar/Navbar";
import ClientSessionProvider from "../signup/ClientSessionProvider";
import Hero from "@/components/hero/Hero";

export const metadata: Metadata = {
  title: "Add Book",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <ClientSessionProvider>
          <Toaster />
          <header>
            <Navbar />
          </header>
          <Hero />
          <main>{children}</main>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
